// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/service/investor.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Raj63/golang-microservices/services/invoices/pkg/model"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockInvestor is a mock of Investor interface.
type MockInvestor struct {
	ctrl     *gomock.Controller
	recorder *MockInvestorMockRecorder
}

// MockInvestorMockRecorder is the mock recorder for MockInvestor.
type MockInvestorMockRecorder struct {
	mock *MockInvestor
}

// NewMockInvestor creates a new mock instance.
func NewMockInvestor(ctrl *gomock.Controller) *MockInvestor {
	mock := &MockInvestor{ctrl: ctrl}
	mock.recorder = &MockInvestorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvestor) EXPECT() *MockInvestorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInvestor) Create(ctx context.Context, investor *model.Investor) (*model.Investor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, investor)
	ret0, _ := ret[0].(*model.Investor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInvestorMockRecorder) Create(ctx, investor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInvestor)(nil).Create), ctx, investor)
}

// Get mocks base method.
func (m *MockInvestor) Get(ctx context.Context, id uuid.UUID) (*model.Investor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.Investor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInvestorMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInvestor)(nil).Get), ctx, id)
}
