version: '3'

services:
  web-portal:
    build:
      context: .
      dockerfile: services/web-portal/Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - db
      - invoices
    environment:
      - APP_ENV=development
      - PRIMARY_DB_URI=postgres://postgres:secret@db:5432/invoices?multiStatements=true&parseTime=true
      - DB_USERNAME=postgres
      - DB_ROOT_USERNAME=postgres
      - DB_PASSWORD=secret
    networks:
      - go-network

  invoices:
    build:
      context: .
      dockerfile: services/invoices/Dockerfile
    ports:
      - 8081:8080
    restart: on-failure
    depends_on:
      - db
    environment:
      - APP_ENV=development
      - PRIMARY_DB_URI=postgres://postgres:secret@db:5432/invoices?multiStatements=true&parseTime=true
      - DB_USERNAME=postgres
      - DB_ROOT_USERNAME=postgres
      - DB_PASSWORD=secret
    networks:
      - go-network

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: invoices
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - go-network
    
volumes:
  postgres-data:

networks:
  go-network:
    driver: bridge
