// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: invoices.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InvoicesService_CreateInvoice_FullMethodName = "/api.InvoicesService/CreateInvoice"
)

// InvoicesServiceClient is the client API for InvoicesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvoicesServiceClient interface {
	CreateInvoice(ctx context.Context, in *CreateInvoiceRequest, opts ...grpc.CallOption) (*CreateInvoiceReply, error)
}

type invoicesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInvoicesServiceClient(cc grpc.ClientConnInterface) InvoicesServiceClient {
	return &invoicesServiceClient{cc}
}

func (c *invoicesServiceClient) CreateInvoice(ctx context.Context, in *CreateInvoiceRequest, opts ...grpc.CallOption) (*CreateInvoiceReply, error) {
	out := new(CreateInvoiceReply)
	err := c.cc.Invoke(ctx, InvoicesService_CreateInvoice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvoicesServiceServer is the server API for InvoicesService service.
// All implementations must embed UnimplementedInvoicesServiceServer
// for forward compatibility
type InvoicesServiceServer interface {
	CreateInvoice(context.Context, *CreateInvoiceRequest) (*CreateInvoiceReply, error)
	mustEmbedUnimplementedInvoicesServiceServer()
}

// UnimplementedInvoicesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInvoicesServiceServer struct {
}

func (UnimplementedInvoicesServiceServer) CreateInvoice(context.Context, *CreateInvoiceRequest) (*CreateInvoiceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInvoice not implemented")
}
func (UnimplementedInvoicesServiceServer) mustEmbedUnimplementedInvoicesServiceServer() {}

// UnsafeInvoicesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvoicesServiceServer will
// result in compilation errors.
type UnsafeInvoicesServiceServer interface {
	mustEmbedUnimplementedInvoicesServiceServer()
}

func RegisterInvoicesServiceServer(s grpc.ServiceRegistrar, srv InvoicesServiceServer) {
	s.RegisterService(&InvoicesService_ServiceDesc, srv)
}

func _InvoicesService_CreateInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoicesServiceServer).CreateInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoicesService_CreateInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoicesServiceServer).CreateInvoice(ctx, req.(*CreateInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InvoicesService_ServiceDesc is the grpc.ServiceDesc for InvoicesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvoicesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.InvoicesService",
	HandlerType: (*InvoicesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInvoice",
			Handler:    _InvoicesService_CreateInvoice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invoices.proto",
}
