CREATE TABLE IF NOT EXISTS currency (
  id SERIAL PRIMARY KEY,
  name VARCHAR,
  code VARCHAR(3),
  symbol VARCHAR(5),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);